version: '3.8'
services:
  frontend:
    build: ./usermanagerfront
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./usermanagerapi
    ports:
      - "5050:5050"
